# Generated by Django 5.2.7 on 2025-10-15 09:56

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Passes', 'Day Care Passes'), ('Packages', 'Grooming Packages'), ('Offers', 'Offers')], help_text='Select a Category', max_length=30)),
                ('slug', models.SlugField(max_length=30, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Service Categories',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('slug', models.SlugField(max_length=30, unique=True)),
                ('img_path', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('alt_text', models.TextField(blank=True, max_length=80)),
                ('description', models.TextField(max_length=200)),
                ('pet_size', models.CharField(blank=True, choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=10, null=True)),
                ('duration', models.DurationField(default=datetime.timedelta(seconds=7200))),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('is_bundle', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='services.servicecategory')),
            ],
            options={
                'verbose_name_plural': ('Services',),
            },
        ),
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.ImageField(upload_to='services/')),
                ('alt_text', models.TextField(blank=True, max_length=120)),
                ('is_main', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='services.service')),
            ],
            options={
                'verbose_name_plural': 'Service Images',
                'ordering': ['sort_order', 'id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_main', True)), fields=('service',), name='unique_main_image_per_service')],
            },
        ),
    ]
