# Generated by Django 5.2.7 on 2025-10-15 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_service_options_alter_service_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='duration',
        ),
        migrations.AddField(
            model_name='service',
            name='duration_hours',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Duration (hours)', max_digits=5),
        ),
    ]
