# Generated by Django 5.2.7 on 2025-10-15 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_remove_service_duration_service_duration_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='duration_hours',
            field=models.DecimalField(blank=True, decimal_places=2, default=1.0, help_text='Duration (hours)', max_digits=5, null=True),
        ),
    ]
