# Generated by Django 5.2.7 on 2025-10-15 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_service_duration_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='pet_size',
        ),
    ]
