# Generated by Django 5.2.7 on 2025-11-17 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_orderitem_price_orderitem_quantity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="service",
        ),
    ]
