# Generated by Django 5.2.7 on 2025-11-21 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_remove_order_service"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voucher",
            name="order_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vouchers",
                to="orders.orderitem",
            ),
        ),
    ]
